integrations:
  last-fm:
    frequency: "daily"
    all: true
  wakatime:
    frequency: "daily"
    all: true
  twitter:
    frequency: "daily"
    all: true
  # spotify:
  #   frequency: "daily"
  #   all: true
  # google-fit:
  #   frequency: "daily"
  #   all: false
  goodreads:
    frequency: "daily"
    all: true
